### ISSUE TITLE
Make problems while installing dslabs on M1 ARM processors.

### ISSUE THREAD

**Issue by Vedaant-Rajoo** [emichael/dslabs#17]
While installing the dslabs framework on my system(M1 Pro Macbook), I came across a few problems.

1. `wget` is not preinstalled on MacBooks and this creates an error where the system fails to make the build files due to the non-presence of `wget`.
2. `gcp` -> This toolkit is a fancy version of `cp` but at the same time is more complicated than `cp`. While running the `gcp` command, the command was unable to find a directory. The change I made was to remove `gcp` and replace it with `cp` in the MakeFile. That solved the problem and I successfully built the framework to work.

I think this should be added to the wiki since most of the students are operating ARM machines. I don't think this is a ARM specific error but maybe `gcp` misbehaves while cherry-picking files and transferring them.
<img width="873" alt="Screen Shot 2022-01-14 at 12 49 59 PM" src="https://user-images.githubusercontent.com/33187221/149562204-f6269794-206b-4d32-aefe-82e63dac83ae.png">

**Comment by emichael** [comment]
The main branch isn't setup for use by students. That Makefile does assume you have some basic utilities installed.

`gcp` is supposed to have the same behavior as GNU `cp` on a Linux machine. It works fine on my Macbook.

**Comment by Vedaant-Rajoo** [comment]
<img width="996" alt="Screen Shot 2022-01-15 at 6 00 36 PM" src="https://user-images.githubusercontent.com/33187221/149640315-57b574b5-40e5-4d2d-ba8b-4d3b75c2a25f.png">

This is the error I got with `gcp`. I understand that the `master` branch is not supposed to be meant for students, but I did come across this problem and my classmates did too.

**Comment by emichael** [comment]
You need `gcp` provided by the coreutils homebrew package. That error just tells you that you don't have anything called `gcp` in your path.
