### ISSUE TITLE
Confusion about the network of dslabs

### ISSUE THREAD

**Issue by LintianShi** [emichael/dslabs#3]
I read Network.java, RunSettings.java, RunState.java and TestSetting.java. But I did not see the code about delays, duplications, and reorderings for messages. Is the network in dslabs not completely asynchronous?

**Comment by emichael** [comment]
Right. The run tests just drop messages; they don't do delays, duplications, or reorderings. (At least for now. I would be open to added some of the latter to the execution environment in the future.)

The network model used in the search tests is completely asynchronous. Implementations need to be able to handle asynchrony to pass those.
