### ISSUE TITLE
Feature Request: add detail messages for more/all invariant predicates

### ISSUE THREAD

**Issue by gnanabit** [emichael/dslabs#34]
Currently, some invariant predicates do not have detail messages. The most prominent one is the [`APPENDS_LINEARIZABLE`](https://github.com/emichael/dslabs/blob/ab243ebfaf16a58cd77ed2c7886babea608ee8af/labs/lab1-clientserver/tst/dslabs/kvstore/KVStoreWorkload.java#L271-L322) predicate. It could be useful to explain why the invariant was violated (e.g., for `APPENDS_LINEARIZABLE`, we could write something like "AppendResult(y) is not a valid result for Append(x)", or "AppendResult(y) for client 2 is inconsistent with AppendResult(x) for client 1"). The other invariant I see is [`MULTI_GETS_MATCH`](https://github.com/emichael/dslabs/blob/ab243ebfaf16a58cd77ed2c7886babea608ee8af/labs/lab4-shardedstore/tst/dslabs/kvstore/TransactionalKVStoreWorkload.java#L260-L277).

These omissions might be intentional (e.g., maybe the goal is to get students to identify what's wrong in the sequence), so I'm not opening a pull request yet.

**Comment by emichael** [comment]
100% just an oversight; something I meant to do but never got around to. I don't think there's any reason not to display a message. If you want to open up a PR, go for it!
