### ISSUE TITLE
Lab 1: clarify what should be done when handling "old requests"

### ISSUE THREAD

**Issue by nathanperkins** [emichael/dslabs#38]
In [this section](https://github.com/emichael/dslabs/tree/handout/labs/lab1-clientserver#part-3-once-and-only-once), it is unclear what is the desired behavior for old requests. I was stuck on this for a bit and figured it out by experimenting with different behaviors until the tests passed.

>You will also need to deal with what happens when the server receives "old" Requests. 

I'd write up suggestions or a PR for how it could be improved but it's possible that the ambiguity is intended to be a part of the challenge.

**Comment by emichael** [comment]
I don’t think there’s any ambiguity. However, figuring out how to implement garbage collection and exactly-once semantics is indeed part of the challenge.
