### ISSUE TITLE
Gradle build fails

### ISSUE THREAD

**Issue by manishrw** [emichael/dslabs#53]
**Describe the bug**
Opening the project in IntelliJ Idea 2023.1 and running the gradle build fails with the below error
> A problem occurred evaluating root project 'dslabs'.
> Could not set unknown property 'classifier' for task ':scaffoldingSourcesJar' of type com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar.

**Screenshots**
![image](https://github.com/emichael/dslabs/assets/1011459/8e54b387-c1a4-4992-82fe-79d6d8e31923)

**Environment**
 - OS: Windows 11
 - JDK (output of `java --version`): OpenJDK 14
 - DSLabs githash: e708af3

**Comment by iefnaf** [comment]
https://github.com/emichael/dslabs/pull/52

**Comment by emichael** [comment]
The project isn't setup to be imported into IntelliJ as a Gradle project. A `.idea` folder is provided though. Instructions on getting a dev environment setup are in https://github.com/emichael/dslabs#contributing
