### ISSUE TITLE
Search Tests Hanging without Logging

### ISSUE THREAD

**Issue by vaibhavb007** [emichael/dslabs#6]
Hi
I am a graduate student at Georgia Tech and we are using these labs as part of our Distributed Computing course. I often see the search tests getting hung up. But when I run them with FINEST logging, they terminate. The earlier hanging up is probably due to some thread getting stuck.
An example being as follows:

`vpb@vpb-Inspiron-7560:~/gatech/sem2/cs7210/assignments/7210-assignments$ ./run-tests.py --lab 3 --test 21
--------------------------------------------------
TEST 21: Single client, no progress in minority [SEARCH] (15pts)

Starting breadth-first search...
	Explored: 0, Depth: 0 (0.01s, 0.00K states/s)
	Explored: 24085, Depth: 7 (5.01s, 4.81K states/s)
	Explored: 59821, Depth: 8 (10.01s, 5.98K states/s)
	Explored: 89775, Depth: 9 (15.05s, 5.96K states/s)
	Explored: 109218, Depth: 9 (20.74s, 5.27K states/s)
	Explored: 147122, Depth: 9 (25.85s, 5.69K states/s)
	Explored: 158166, Depth: 9 (30.00s, 5.27K states/s)
Search finished.

Starting breadth-first search...
	Explored: 1, Depth: 0 (0.00s, 1.00K states/s)
	Explored: 37368, Depth: 173 (6.74s, 5.54K states/s)
	Explored: 82224, Depth: 256 (17.14s, 4.80K states/s)
	Explored: 103777, Depth: 288 (28.56s, 3.63K states/s)
	Explored: 113273, Depth: 301 (30.00s, 3.78K states/s)
Search finished.

...PASS (60.32s)
==================================================

Tests passed: 1/1
Points: 15/15 (100.00%)
Total time: 60.331s

ALL PASS
==================================================
vpb@vpb-Inspiron-7560:~/gatech/sem2/cs7210/assignments/7210-assignments$ ./run-tests.py --lab 3 --test 21
--------------------------------------------------
TEST 21: Single client, no progress in minority [SEARCH] (15pts)

Starting breadth-first search...
	Explored: 0, Depth: 0 (0.01s, 0.00K states/s)
	Explored: 21888, Depth: 7 (5.01s, 4.37K states/s)
	Explored: 25142, Depth: 7 (10.01s, 2.51K states/s)
	Explored: 25142, Depth: 7 (15.01s, 1.68K states/s)
	Explored: 25142, Depth: 7 (20.01s, 1.26K states/s)
	Explored: 25142, Depth: 7 (25.01s, 1.01K states/s)
^CTraceback (most recent call last):
  File "./run-tests.py", line 183, in <module>
    main()
  File "./run-tests.py", line 179, in main
    assertions=args.assertions)
  File "./run-tests.py", line 90, in run_tests
    subprocess.call(command)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 1099, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 125, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
`
But when I run these with logging enabled, they consistently pass. Is there any framework issue related to this?

**Comment by emichael** [comment]
This is almost always because there is excessive synchronization. The READMEs describe the requirements on student code. In particular, `Hashtable` should not be used.
