### ISSUE TITLE
ubuntu make fails; windows 11 gradlew.bat fails

### ISSUE THREAD

**Issue by cubbins** [emichael/dslabs#74]
ubuntu 
java -version ok
javac -version ok
make fails

windows 11
java -version ok
javac -vesion ok
gradlew.bat fails.

Non-working after first command issued, for both Ubuntu and Windows 11, following install with git clone https://github.com/emichael/dslabs.git

![ubuntu_error](https://github.com/user-attachments/assets/567b18df-0162-4174-8dea-ef2902221303)
![windows11_dslabs](https://github.com/user-attachments/assets/b69a7494-9b2e-496b-8666-142f2ae81e26)

**Describe the bug**
A clear and concise description of what the bug is. Please be as specific as possible and make sure you've read the project's documentation in its entirety before submitting.

**Screenshots**

**Environment**
 - OS: [e.g. Linux, MacOS]
 - JDK (output of `java --version`):
 - DSLabs githash:

**Comment by emichael** [comment]
You’re trying to compile Java 17 with JVM 11. 17 is the minimum supported Java version.

**Comment by cubbins** [comment]
Yes, I have it now. Thank you.
________________________________
