### ISSUE TITLE
Visual Debugger

### ISSUE THREAD

**Issue by raafatseif** [emichael/dslabs#8]
Hello, how long should it take until the list of servers appears and is ready to start the visual debugger? It stays pending for me. I ran `python3 run-tests.py --lab 0 --debug 1 1 GET:foo` and `python3 run-tests.py --lab 1 --debug 1 1 GET:foo`. Are we supposed to implement anything first? I have not modified the code yet.

Environment:
Python: 3.7.3
Java:
openjdk 14 2020-03-17
OpenJDK Runtime Environment (build 14+36-1461)
OpenJDK 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)
OS: Debian GNU/Linux 10 (buster)
browser: Google Chrome 87.0.4280.88

![image](https://user-images.githubusercontent.com/32026171/103777463-86613a00-4ff6-11eb-8415-de764b243faf.png)

**Comment by raafatseif** [comment]
I managed to get the visual debugger to work. I have a different setup now, running it in WSL.

**Comment by emichael** [comment]
@raafatseif Sorry for not responding to the previous. Glad you got it working, but I'm confused about what went wrong in Linux. You weren't able to click "Debugger > Debug system" in the top right corner? Any output in the terminal?

**Comment by raafatseif** [comment]
Hi  @emichael ! No worries. I initially setup the environment on a remote machine with Python3 and openjdk-14 so that I do not have to install them on my local machine. I SSH'd into it, forwarded port 3000 and ran the visual debugger. I was not able to click Debugger > Debug system, the button was not activated.
Here's the output from the terminal:
 
![image](https://user-images.githubusercontent.com/32026171/104024368-a0328680-5188-11eb-9dfa-ecc93850be2f.png)

**Comment by raafatseif** [comment]
It looks like it works now after forwarding port 5000 as well!

**Comment by kprav33n** [comment]
I'm running this on a remote SSH server as well. I tried forwarding ports 3000 and 5000 of the SSH server to my laptop. With this, I'm able to attach using "Debugger > Debug System". But, I'm unable to step forward by clicking "Next event". Is there any other ports that I have to forward as well? What are the different ports used by the visualizer and how they are used? I also see some reference to port 4343.
